### ISSUE TITLE
how would i upload from my iphone?

### ISSUE THREAD

**Issue by ralyodio** [rlue/xferase#1] opened 2021-12-11 09:22 UTC
Looking for a replacement for icloud

**Comment by rlue** [comment] 2021-12-11 09:54
This question is addressed in [this guide](https://github.com/rlue/xferase/blob/master/guides/upload-phone.md#-what-about-iphone).

To my knowledge, it's not really possible—you can copy files from your iPhone onto your computer with Dropbox or similar, but you can't really automatically manage the iPhone's camera roll using third-party software (_e.g.,_ add pictures to or delete pictures from the camera). AFAIK this is a feature, not a bug (of iOS).

**Closed as completed by rlue** 2021-12-11 09:54 UTC
